### ISSUE TITLE
Crashing Upon Opening

### ISSUE THREAD

**Issue by PasswordOnOsu** [flathub/sh.ppy.osu#112]
I use Fedora if that means anything. Whenever I'd try to open the game, it would just crash. So I ran it in the terminal `flatpak run sh.ppy.osu` and this popped up as the error:
```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at osu.Framework.Input.Handlers.Tablet.OpenTabletDriverHandler.Initialize(GameHost host)
   at osu.Framework.Platform.GameHost.initialiseInputHandlers()
   at osu.Framework.Platform.GameHost.Run(Game game)
   at osu.Desktop.Program.Main(String[] args) in /home/runner/work/osu-auth-client/osu-auth-client/osu/osu.Desktop/Program.cs:line 120
```
I didn't know if it was just my computer or the flatpak itself so I asked my friend if they could run lazer on their flatpak and they also got the same error. I'm not a very tech savvy person so if I'm requested to do anything, I'm most likely not going to know how to do it.

**Comment by peppy** [comment]
You may not be tech savvy, but please at least learn to search. https://github.com/ppy/osu/discussions/23900
