### ISSUE TITLE
Broken video decoding

### ISSUE THREAD

**Issue by ttcchhmm** [flathub/sh.ppy.osu#34]
The game fails to decode the videos. The `runtime.log` file contains these lines pointing to an issue with `avformat` :
```
2022-05-14 11:50:20 [verbose]: VideoDecoder faulted: System.DllNotFoundException: Unable to load shared library 'avformat' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libavformat: cannot open shared object file: No such file or directory
2022-05-14 11:50:20 [verbose]: at System.Runtime.InteropServices.NativeLibrary.LoadByName(String libraryName, QCallAssembly callingAssembly, Boolean hasDllImportSearchPathFlag, UInt32 dllImportSearchPathFlag, Boolean throwOnError)
2022-05-14 11:50:20 [verbose]: at System.Runtime.InteropServices.NativeLibrary.LoadLibraryByName(String libraryName, Assembly assembly, Nullable`1 searchPath, Boolean throwOnError)
2022-05-14 11:50:20 [verbose]: at System.Runtime.InteropServices.NativeLibrary.Load(String libraryName, Assembly assembly, Nullable`1 searchPath)
2022-05-14 11:50:20 [verbose]: at osu.Framework.Graphics.Video.VideoDecoder.<>c.<CreateFuncs>b__66_0(String name)
2022-05-14 11:50:20 [verbose]: at FFmpeg.AutoGen.ffmpeg.<>c.<.cctor>b__6_344(Byte* buffer, Int32 buffer_size, Int32 write_flag, Void* opaque, avio_alloc_context_read_packet_func read_packet, avio_alloc_context_write_packet_func write_packet, avio_alloc_context_seek_func seek)
2022-05-14 11:50:20 [verbose]: at FFmpeg.AutoGen.ffmpeg.avio_alloc_context(Byte* buffer, Int32 buffer_size, Int32 write_flag, Void* opaque, avio_alloc_context_read_packet_func read_packet, avio_alloc_context_write_packet_func write_packet, avio_alloc_context_seek_func seek)
2022-05-14 11:50:20 [verbose]: at osu.Framework.Graphics.Video.VideoDecoder.prepareDecoding()
2022-05-14 11:50:20 [verbose]: at osu.Framework.Graphics.Video.VideoDecoder.StartDecoding()
```

When I run the game with `LD_DEBUG=files` (I used `flatpak run --env=LD_DEBUG=files sh.ppy.osu &> /tmp/osu.log`) and searched for `avformat` I found the following line that seemed suspicious :
```
/app/lib/libavformat.so: error: symbol lookup error: undefined symbol: avpriv_packet_list_get, version LIBAVCODEC_58 (fatal)
```

The AppImage build is not affected so this is a Flatpak related issue.

**Comment by pizzadude** [comment]
Workaround I found for now:

Download the AppImage
./osu.AppImage --appimage-extract
Download compat-ffmpeg4 from rpmfusion if you use Fedora but otherwise download the correct ffmpeg 4 package from your distro
Replace the libraries in the osu AppImage extracted directory with the ones from the compat-ffmpeg4 package
run osu with ./AppRun
then videos should work

**Comment by peppy** [comment]
We now bundle ffmpeg with the game. This should not be required.

**Comment by ttcchhmm** [comment]
> The AppImage now crashes when playing a song with videos.
> 
> Workaround I found for now:
> 
> Download the AppImage ./osu.AppImage --appimage-extract Download compat-ffmpeg4 from rpmfusion if you use Fedora but otherwise download the correct ffmpeg 4 package from your distro Replace the libraries in the osu AppImage extracted directory with the ones from the compat-ffmpeg4 package run osu with ./AppRun then videos should work

I tried to reproduce this but I wasn't able to crash the game when using the AppImage on Arch Linux (even when uninstalling the `ffmpeg4.4` package). The Flatpak package still doesn't have videos but at least the game doesn't crash.

**Comment by pizzadude** [comment]
> We now bundle ffmpeg with the game. This should not be required.

```
./osu.AppImage
malloc(): unsorted double linked list corrupted
fish: Job 1, './osu.AppImage' terminated by signal SIGABRT (Abort)
```
This is when trying to play the video version of https://osu.ppy.sh/beatmapsets/6687#osu/29955 in Fedora 36 KDE Wayland, with the latest osu AppImage.

**Comment by pizzadude** [comment]
![image](https://user-images.githubusercontent.com/1454420/169941641-0db9672e-cbae-4b0a-b131-d019e867600a.png)

Edit: Fixed by doing "sudo ln -s /usr/lib64/libbz2.so /usr/lib64/libbz2.so.1.0"

Now it works.

**Comment by peppy** [comment]
Should also be resolved our end in the next release (https://github.com/ppy/osu-framework/pull/5198).

**Comment by pizzadude** [comment]
@ttcchhmm I tested the latest flatpak and video playback works again. Can you test?

**Comment by ttcchhmm** [comment]
I just tested the latest Flatpak too (`sh.ppy.osu` version `2022.528.0`) and I also get the videos. This issue is fixed.
